SET NAMES utf8;
USE `fuel_dev`;

CREATE TABLE imas_characters_image (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL
);

INSERT INTO imas_characters_image (image, name)
VALUES
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/haruka.jpg', '春香'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/chihaya.jpg', '千早'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/miki.jpg', '美希'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/yukiho.jpg', '雪歩'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/yayoi.jpg', 'やよい'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/makoto.jpg', '真'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/iori.jpg', '伊織'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/takane.jpg', '貴音'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/ritsuko.jpg', '律子'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/azusa.jpg', 'あずさ'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/ami.jpg', '亜美'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/mami.jpg', '真美'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/hibiki.jpg', '響'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/mirai.jpg', '未来'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/shizuka.jpg', '静香'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/tsubasa.jpg', '翼'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/kotoha.jpg', '琴葉'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/elena.jpg', 'エレナ'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/minako.jpg', '美奈子'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/megumi.jpg', '恵美'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/matsuri.jpg', 'まつり'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/serika.jpg', '星梨花'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/akane.jpg', '茜'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/anna.jpg', '杏奈'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/roco.jpg', 'ロコ'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/yuriko.jpg', '百合子'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/sayoko.jpg', '紗代子'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/arisa.jpg', '亜利沙'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/umi.jpg', '海美'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/iku.jpg', '育'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/tomoka.jpg', '朋花'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/emily.jpg', 'エミリー'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/shiho.jpg', '志保'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/ayumu.jpg', '歩'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/hinata.jpg', 'ひなた'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/kana.jpg', '可奈'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/nao.jpg', '奈緒'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/chizuru.jpg', '千鶴'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/konomi.jpg', 'このみ'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/tamaki.jpg', '環'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/fuka.jpg', '風花'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/miya.jpg', '美也'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/noriko.jpg', 'のり子'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/mizuki.jpg', '瑞希'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/karen.jpg', '可憐'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/rio.jpg', '莉緒'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/subaru.jpg', '昴'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/reika.jpg', '麗花'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/momoko.jpg', '桃子'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/julia.jpg', 'ジュリア'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/tsumugi.jpg', '紬'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/kaori.jpg', '歌織'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/kotori.jpg', '小鳥'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/misaki.jpg', '美咲'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/producer.jpg', 'プロデューサー'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/takagi.jpg', '社長'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/sora.jpg', 'そら'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/sika.jpg', '詩花'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/leon.jpg', '玲音'),
  ('https://raw.githubusercontent.com/tankarup/ML-4koma-viewer/main/icons/kuroi.jpg', '黒井社長');
